[package]
name = "hullcaster"
version = "0.1.0"
authors = ["gilcu3"]
edition = "2021"
license = "GPL-3.0-or-later"
description = "A terminal-based podcast manager to subscribe to and play podcasts with gpodder sync support."
keywords = ["podcast", "terminal", "TUI", "curses", "gpodder"]
categories = ["multimedia::audio", "command-line-interface"]

homepage = "https://github.com/gilcu3/hullcaster"
repository = "https://github.com/gilcu3/hullcaster"
documentation = "https://github.com/gilcu3/hullcaster"
readme = "README.md"

[dependencies]
crossterm = "0.23.0"
rss = "2.0.0"
rusqlite = "0.26.3"
ureq = { version = "2.4.0", features = ["cookies", "native-certs"] }
native-tls = { version = "0.2.8", optional = true }
clap = { version = "3.1.2", features = ["cargo", "env"] }
toml = "0.5.8"
anyhow = "1.0.55"
serde = { version = "1.0.136", features = ["derive"] }
chrono = "0.4.19"
regex = "1.5.4"
sanitize-filename = "0.3.0"
shellexpand = "2.1.0"
dirs = { package = "dirs-next", version = "2.0.0" }
opml = "1.1.3"
ahash = "0.7.6"
nohash-hasher = "0.2.0"
unicode-segmentation = "1.8.0"
textwrap = "0.14.2"
escaper = "0.1.1"
rfc822_sanitizer = "0.3.6"
semver = "1.0.6"
base64 = "0.21.7"
serde_json = {version = "1.0.116"}
log = "0.4.21"
simplelog = {version = "0.12.2", features = ["local-offset"]}
symphonia = { version = "0.5.4", features = ["mp3"] }
once_cell = "1.19.0"
