[package]
name = "shellcaster"
version = "0.6.0"
authors = ["Jeff Hughes <jeff.hughes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pancurses = "0.16.1"
rusqlite = "0.21.0"
rss = { version = "1.9.0", features = ["from_url"] }
reqwest = "0.10.4"
futures = "0.3.4"
tokio = { version = "0.2", features = ["macros"] }
toml = "0.5.6"
serde = "1.0.106"
chrono = "0.4.11"
rfc822_sanitizer = "0.3.3"
lazy_static = "1.4.0"
regex = "1.3.6"
shellexpand = "2.0.0"
dirs = { package = "dirs-next", version = "1.0.1" }